### PR TITLE
fix semver-checks with lack of `alpha()` function

### PR DESCRIPTION
**Pull request by ripytide**

### CODE REVIEW

**Comment by ripytide** [comment]
Hmm, adding back the inherent `alpha()` method then causes conflict with the `HasAlpha::alpha()` trait method. Do we just use fully qualified syntax for calling it until the old legacy methods get removed when bump the major version?

**Comment by kornelski** [comment]
Is this meant for 0.8 or 0.9?

I assume fixing deprecation warnings on 0.8 is a prerequisite to upgrading to 0.9, so 0.9 won't need this method.

**Comment by ripytide** [comment]
Oh I didn't know that multiple branches were being maintained, I'd thought we had decided to release the new stuff as the `0.8` version in #113 so there's now only one branch with all the legacy thing being deprecated?

**Comment by kornelski** [comment]
I've mistakenly assumed that Cargo would allow testing 0.8-alpha with 0.8 crates, but to my dismay it won't unify them. 

This makes it hard to have public beta testing of the changes, and I'm afraid of just YOLOing everything from the 0.9 branch. So I've been releasing changes piecemeal on 0.8 where possible.

**Comment by ripytide** [comment]
We could do a sort of YOLO release but then quickly patch any issues that came up similarly to how #116 was handled? Not that many people update that regularly so if we were quick enough with the patches/testing we could probably get away with it?

**Comment by ripytide** [comment]
If we agree on the approach to release this branch on the `v0.8`, would you like me to prune out the `legacy` feature?

**Pull request merged**
